### ISSUE TITLE
3.x: Driver Matrix is ignoring certain skip marks

### ISSUE THREAD

**Issue by k0machi** [scylladb/scylla-java-driver-matrix#34]
Some tests on 3.x branch have a special `ScyllaSkip` marker (due to unsupported features and such) on some tests. However, it seems that this marker is ignored by driver matrix pipelines, causing some of those tests to run (and subsequently fail):

[Example](https://github.com/scylladb/java-driver/blob/scylla-3.x/driver-core/src/test/java/com/datastax/driver/core/ReconnectionTest.java#L83-L89)

Test: beforeTestMethod[public void com.datastax.driver.core.ReconnectionTest.should_keep_reconnecting_on_authentication_error() throws java.lang.InterruptedException](0)
Class: 3.11.5.0.com.datastax.driver.core.ReconnectionTest
 ```Timeout after 5 minutes while waiting for condition (java.lang.AssertionError)```

**Comment by fruch** [comment]
Maybe it's assume something about the scylla version ? Expecting it to be release:5.2, I know the python driver has such things.

**Comment by k0machi** [comment]
> Maybe it's assume something about the scylla version ? Expecting it to be release:5.2, I know the python driver has such things.

I'll try running this with release:5.2 instead of master, let's see what happens

**Comment by k0machi** [comment]
> > Maybe it's assume something about the scylla version ? Expecting it to be release:5.2, I know the python driver has such things.
> 
> I'll try running this with release:5.2 instead of master, let's see what happens

Didn't help, same issue.

**Comment by k0machi** [comment]
Running with a debugger I can see that the annotation is ignored when particular test groups are selected (at least I think that's what happening)
