### ISSUE TITLE
[Scylla-5.2] 3 more (2 are SNI-feature related) failing tests than using a `scylla-master`

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-java-driver-matrix#37]
Running the [scylla-5.2/driver-tests/java-driver-matrix-test#33](https://argus.scylladb.com/test/688b82d4-ad53-4e40-bcd1-fc77b007e84c/runs?additionalRuns[]=81e55f4e-21c9-4fb7-8e0a-35e31a5ab7cc) CI job appeared following errors which are absent in the recent scylla-master test runs:

1) Test: should_call_onAdd_with_bootstrap_stop_start
Class: 3.11.5.0.com.datastax.driver.core.NodeRefreshDebouncerTest
```
Wanted but not invoked:
stateListener.onAdd(<Capturing argument>);
-> at com.datastax.driver.core.NodeRefreshDebouncerTest.should_call_onAdd_with_bootstrap_stop_start(NodeRefreshDebouncerTest.java:63)

However, there were other interactions with this mock:
stateListener.onRegister(
    com.datastax.driver.core.Cluster@30f71b30
);
-> at com.datastax.driver.core.Cluster.register(Cluster.java:518)

stateListener.onUp(/127.0.1.2:37827);
-> at com.datastax.driver.core.Cluster$Manager.onUp(Cluster.java:2127)

 (Wanted but not invoked)
```

2) Test: beforeTestMethod[public void com.datastax.driver.core.ScyllaSniProxyTest.test_ccm_cluster_1node() throws java.lang.InterruptedException](0)
Class: 3.11.5.0.com.datastax.driver.core.ScyllaSniProxyTest
 ```
The command ccm start  --sni-proxy --sni-port 41671 --config-dir=/tmp/1704313918616-0 failed to execute (java.lang.AssertionError)
```

3) Test: beforeTestMethod[public void com.datastax.driver.core.ScyllaSniProxyTest.test_ccm_cluster_3node() throws java.lang.InterruptedException](0)
Class: 3.11.5.0.com.datastax.driver.core.ScyllaSniProxyTest
 ```
The command ccm start  --sni-proxy --sni-port 44515 --config-dir=/tmp/1704313957299-0 failed to execute (java.lang.AssertionError)
```

Screenshots:

![Screenshot from 2024-01-08 15-44-12](https://github.com/scylladb/scylla-java-driver-matrix/assets/3796058/594dc7ce-8e3b-4091-a4b2-780dc9b099f6)

![Screenshot from 2024-01-08 15-44-22](https://github.com/scylladb/scylla-java-driver-matrix/assets/3796058/9a285bc1-827f-48ac-ac98-cc099f46d92a)

[Argus](https://argus.scylladb.com/test/688b82d4-ad53-4e40-bcd1-fc77b007e84c/runs?additionalRuns[]=81e55f4e-21c9-4fb7-8e0a-35e31a5ab7cc), [CI](https://jenkins.scylladb.com/job/scylla-5.2/job/driver-tests/job/java-driver-matrix-test/33)

**Comment by fruch** [comment]
```
(EE) No appropriate python interpreter found.(EE) No appropriate python interpreter found.generating keystore.jks
```

looks like we are missing python2 on the docker image
