### ISSUE TITLE
`should_send_down_notifications_after_init_when_contact_points_are_down` should be ignored on scylla

### ISSUE THREAD

**Issue by k0machi** [scylladb/scylla-java-driver-matrix#47]
This test doesn't really work for scylla since it tests very specific cassandra behaviour (that's not guaranteed on cassandra either), so we should ignore it.

Test: should_send_down_notifications_after_init_when_contact_points_are_down
Class: 3.11.4.0.com.datastax.driver.core.LoadBalancingPolicyBootstrapTest
 ```
Expecting:
 <[Entry(action=INIT, host=/127.0.1.1:37949), Entry(action=ADD, host=/127.0.1.2:37949)]>
to contain only:
 <[Entry(action=INIT, host=/127.0.1.1:37949), Entry(action=INIT, host=/127.0.1.2:37949)]>
elements not found:
 <[Entry(action=INIT, host=/127.0.1.2:37949)]>
and elements not expected:
 <[Entry(action=ADD, host=/127.0.1.2:37949)]>
 (java.lang.AssertionError)```

**Comment by dimakr** [comment]
@dkropachev can we plan adding this to patches?
The issue keeps repeating and its recent manifestation is failing test on 2024.1.8 release testing, as mentioned in https://github.com/scylladb/java-driver/issues/219

**Comment by dkropachev** [comment]
> @dkropachev can we plan adding this to patches? The issue keeps repeating and its recent manifestation is failing test on 2024.1.8 release testing, as mentioned in [scylladb/java-driver#219](https://github.com/scylladb/java-driver/issues/219)

Sure, I will schedule it.
