### ISSUE TITLE
[Scylla-5.2] `should_call_onAdd_with_bootstrap_stop_start` test started failing using `3.11.5.2` and `3.11.4.0` versions

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-java-driver-matrix#48]
Running the [scylla-5.2/driver-tests/java-driver-matrix-test#38](https://argus.scylladb.com/test/688b82d4-ad53-4e40-bcd1-fc77b007e84c/runs?additionalRuns[]=42d32e9d-3f20-4b8c-b400-728e8812f894) CI job the `should_call_onAdd_with_bootstrap_stop_start` test failed using `3.11.5.2` and `3.11.4.0` versions:

```
should_call_onAdd_with_bootstrap_stop_start
3.11.5.2.com.datastax.driver.core.NodeRefreshDebouncerTest

Wanted but not invoked:
stateListener.onAdd(<Capturing argument>);
-> at com.datastax.driver.core.NodeRefreshDebouncerTest.should_call_onAdd_with_bootstrap_stop_start(NodeRefreshDebouncerTest.java:63)

However, there were other interactions with this mock:
stateListener.onRegister(
    com.datastax.driver.core.Cluster@3d65fbab
);
-> at com.datastax.driver.core.Cluster.register(Cluster.java:518)

stateListener.onUp(/127.0.1.2:43329);
-> at com.datastax.driver.core.Cluster$Manager.onUp(Cluster.java:2127)

 (Wanted but not invoked)
```

Screenshot:
![Screenshot from 2024-04-22 13-53-10](https://github.com/scylladb/scylla-java-driver-matrix/assets/3796058/53aace7b-e42c-4380-a6de-a1d10c5f52a3)

This test doesn't fail using `master` scylla in latest runs.

**Comment by vponomaryov** [comment]
@fruch is it correct place to file this bug? Or java-driver repo should have been used for it?

**Comment by fruch** [comment]
> @fruch is it correct place to file this bug? Or java-driver repo should have been used for it?

Since it seems to be an issue with our fork versions, it should be reported on java-driver 

Also from the sounds of it it might even be a scylla regression

**Comment by vponomaryov** [comment]
> > @fruch is it correct place to file this bug? Or java-driver repo should have been used for it?
> 
> Since it seems to be an issue with our fork versions, it should be reported on java-driver
> 
> Also from the sounds of it it might even be a scylla regression

Created it there: https://github.com/scylladb/java-driver/issues/292
